include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_relative_lib_imports: error

linter:
  rules:
    non_constant_identifier_names: false
    constant_identifier_names: true

formatter:
  trailing_commas: preserve
  page_width: 140