// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvGtniAy5ir2CcA34sFXwWklfXILpPkQk',
    appId: '1:692741382499:web:6ab9445a872c5d104df356',
    messagingSenderId: '692741382499',
    projectId: 'coup-7ae2e',
    authDomain: 'coup-7ae2e.firebaseapp.com',
    databaseURL: 'https://coup-7ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'coup-7ae2e.firebasestorage.app',
    measurementId: 'G-70T039PT3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Z8uO_iQR39bLdUsgE9KuxzbGl04paJc',
    appId: '1:692741382499:android:b61f2c5caf881b294df356',
    messagingSenderId: '692741382499',
    projectId: 'coup-7ae2e',
    databaseURL: 'https://coup-7ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'coup-7ae2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Wb7ey_LGoB_f5_xHINQ0ZeU4hjBUbBo',
    appId: '1:692741382499:ios:b0d1b53e2dcba2584df356',
    messagingSenderId: '692741382499',
    projectId: 'coup-7ae2e',
    databaseURL: 'https://coup-7ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'coup-7ae2e.firebasestorage.app',
    iosBundleId: 'com.example.coup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Wb7ey_LGoB_f5_xHINQ0ZeU4hjBUbBo',
    appId: '1:692741382499:ios:b0d1b53e2dcba2584df356',
    messagingSenderId: '692741382499',
    projectId: 'coup-7ae2e',
    databaseURL: 'https://coup-7ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'coup-7ae2e.firebasestorage.app',
    iosBundleId: 'com.example.coup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvGtniAy5ir2CcA34sFXwWklfXILpPkQk',
    appId: '1:692741382499:web:41b241b956e5e7464df356',
    messagingSenderId: '692741382499',
    projectId: 'coup-7ae2e',
    authDomain: 'coup-7ae2e.firebaseapp.com',
    databaseURL: 'https://coup-7ae2e-default-rtdb.firebaseio.com',
    storageBucket: 'coup-7ae2e.firebasestorage.app',
    measurementId: 'G-ZSBLPZW5V8',
  );
}
